@ExtCharlist_HostAddress = https://localhost:7189


GET {{ExtCharlist_HostAddress}}/api/character

###

GET {{ExtCharlist_HostAddress}}/api/character

###

POST {{ExtCharlist_HostAddress}}/api/character
Content-Type: application/json

{
  "CharacterName": "Gimley",
  "CharacterClass":{
             "ClassName":"fighter"
             },
  "CharacterRace":{
             "RaceName":"dwarf"
  }


}

###

GET {{ExtCharlist_HostAddress}}/api/character/

###

GET {{ExtCharlist_HostAddress}}/api/characterrace

###

POST {{ExtCharlist_HostAddress}}/api/characterrace
Content-Type: application/json

{
  "Id":"WRLIGFGEBRGLIAEUGBALIEGBAERLIGABEGRLIAERBGALIU"
  "RaceName":"Elf"
}

###

POST {{ExtCharlist_HostAddress}}/api/characterrace
Content-Type: application/json

{
  //CharacterRace
}

###

@userId=string
GET {{ExtCharlist_HostAddress}}/api/Character/{{userId}}

###

GET {{ExtCharlist_HostAddress}}/api/character/GetByUser/{userId:length(24)}?userId={{userId}}

###

@id=string
GET {{ExtCharlist_HostAddress}}/api/Character/Get/{{id}}

###

GET {{ExtCharlist_HostAddress}}/api/Character/GetByUser/

###

GET {{ExtCharlist_HostAddress}}/api/character/GetByUser/{{id}}

###

GET {{ExtCharlist_HostAddress}}/{{id}}

###

GET {{ExtCharlist_HostAddress}}/api/Character/GetByUser/ghjj

###
